# Generated by Django 5.0.3 on 2024-04-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='component_image',
            field=models.ImageField(upload_to='components/images/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
