# Generated by Django 5.0.3 on 2024-04-04 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_order_end_date_order_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('quality', models.CharField(max_length=100, verbose_name='Качество')),
                ('guarantee', models.CharField(max_length=100, verbose_name='Гарантия')),
                ('status', models.CharField(max_length=100, verbose_name='Состояние')),
                ('delivery', models.CharField(max_length=100, verbose_name='Доставка')),
                ('code', models.CharField(max_length=100, verbose_name='Номер детали')),
                ('answer_image', models.ImageField(upload_to='components/images/%Y/%m/%d/', verbose_name='Изображение')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='accounts.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ответ на заказ',
                'verbose_name_plural': 'Ответы на заказ',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.answer'),
        ),
    ]
