# Generated by Django 5.0.3 on 2024-04-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_answer_order_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_image',
            field=models.ImageField(upload_to='answers/images/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
